#%RAML 1.0
types:
  Category:
    description: Product category
    type: !include

      
  Product:
    description: Main resource type
    type: !include data-types/product.raml

title: Music Store System API
description: Music Store System API sole purpose is to fetch data from DB and/or store data in DB.
mediaType:
  - application/json
version: v1
protocols:
  - HTTP
/products:
  get:
    displayName: GET all products
    description: Retrieves all products from database
    responses:
      "200":
        body:
          items:
            type: Product
