#%RAML 1.0 Trait

queryParameters:
  sort:
    description: |
      Order by one of the following fields - id, sku, name, unit_price 
    type: string
    enum: [id, sku, name, unit_price]
    default: id
    required: false
    example: name
  order:
    description: Order
    enum: [desc, asc]
    default: asc
    required: false
    example: desc